name: Shellcheck

on:
  push:
    paths:
      - "bootstrap.sh"
      - "scripts/**/*.sh"
      - ".github/workflows/shellcheck.yml"
  pull_request:
    paths:
      - "bootstrap.sh"
      - "scripts/**/*.sh"
      - ".github/workflows/shellcheck.yml"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run shellcheck
        run: shellcheck bootstrap.sh scripts/*.sh
